artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Shajid-M/miscData/raw/main/summarizer-data.zip
  local_data_file: arttifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
